name: Deploy React Application

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  linters:
    name: Run linters ESLint and Stylelint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Install dependencies
        run: npm install
      
      - name: Run ESLint
        run: npm run lint

      - name: Run Stylelint
        run: npm run lint:styles

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: linters

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        env:
          PUBLIC_URL: /Trybe-project-trybewallet
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build